# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bUcihELTFm83PNGqarumnz8KLpTjF0kO
"""

import streamlit as st
import numpy as np
import joblib

# Load saved model and scaler
model = joblib.load('diabetes_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("Diabetes Risk Screening Tool")
st.write("Enter patient details to assess diabetes risk.")

# Input fields
pregnancies = st.number_input("Pregnancies", min_value=0, max_value=20, value=1)
glucose = st.number_input("Glucose (mg/dL)", min_value=0, max_value=1000, value=120)


# After — clinically accurate
blood_pressure = st.number_input("Diastolic Blood Pressure (mm Hg)", 
                                  min_value=0, max_value=150, value=70,
                                  help="Enter the diastolic (lower) value only. e.g. if BP is 120/80, enter 80")
skin_thickness = st.number_input("Skin Thickness (mm)", min_value=0, max_value=100, value=20)
insulin = st.number_input("Insulin (μU/mL)", min_value=0, max_value=900, value=80)
bmi = st.number_input("BMI", min_value=0.0, max_value=70.0, value=25.0)
dpf = st.number_input("Diabetes Pedigree Function", min_value=0.0, max_value=3.0, value=0.5)
age = st.number_input("Age", min_value=1, max_value=120, value=30)

if st.button("Assess Risk"):
    # Prepare input and scale
    input_data = np.array([[pregnancies, glucose, blood_pressure,
                            skin_thickness, insulin, bmi, dpf, age]])
    input_scaled = scaler.transform(input_data)

    # Predict with threshold 0.4
    probability = model.predict_proba(input_scaled)[0][1]
    risk = "HIGH RISK" if probability >= 0.4 else "LOW RISK"

    st.markdown(f"### Result: {risk}")
    st.write(f"Probability of diabetes: **{probability:.1%}**")

    if probability >= 0.4:
        st.warning("This patient should be referred for further diagnostic testing (HbA1c, fasting glucose).")
    else:
        st.success("Low risk — routine monitoring recommended.")

    st.caption("This tool is a screening aid only, not a diagnostic confirmation.")
#**Step 4 — Run it**#
#streamlit run app.py#
